name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Debug - List Files
        run: ls -R  # Print all files in runner

      - name: Build Frontend Docker Image
        run: docker build -t mickeydoe/projecttwo_front-end:latest ./front-end

      - name: Push Image to Docker Hub
        run: docker push mickeydoe/projecttwo_front-end:latest

      # 📧 SUCCESS EMAIL NOTIFICATION
      - name: Send Email on Success
        if: success()
        uses: mattnotmitt/mailer@v3.0.0
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "✅ SUCCESS: Docker Image Built & Pushed!"
          body: "Hello,\n\nThe frontend Docker image has been successfully built and pushed to Docker Hub.\n\nRepository: mickeydoe/projecttwo_front-end\n\nBest,\nGitHub Actions"
          from: "GitHub Actions <${{ secrets.SMTP_USERNAME }}>"
          to: ${{ secrets.EMAIL_TO }}

      # 📧 FAILURE EMAIL NOTIFICATION
      - name: Send Email on Failure
        if: failure()
        uses: mattnotmitt/mailer@v3.0.0
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "❌ FAILURE: Docker Build Failed!"
          body: "Hello,\n\nThe frontend Docker build has FAILED. Please check the logs in GitHub Actions.\n\nBest,\nGitHub Actions"
          from: "GitHub Actions <${{ secrets.SMTP_USERNAME }}>"
          to: ${{ secrets.EMAIL_TO }}
